# Generated by Django 3.2.5 on 2021-07-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('systematic_name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
